### ISSUE TITLE
Support custom Object creation

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#104]
For like when create and `WC_Product_Simple` or `WC_Product_Variable`. This is al a CPT > `WC_Product`.

@NielsdeBlaauw suggest https://github.com/level-level/Clarkson-Core/pull/103

**Comment by jmslbam** [comment]
@NielsdeBlaauw With the removal of this `in_array( $type, $cc->autoloader->post_types )` can't you fix this by using `$type = apply_filters( 'clarkson_object_type', $type );`?

**Comment by jmslbam** [comment]
I really don't understand why we are registering all the post_types, taxonomies, user_types and in this case extra's.
Yes we are checking them if they are registered, but a class_exists would be suffiencient, and if it a `$type` is in the array of registered items, then it will always run the `class_exists`.

You said, the `in_array` is faster if `$type` has an invalid , but in wat situation will that so?
Maybe `_built_in` CPT's like menu's? 

So, why is all this registering and checking needed?

**Comment by NielsdeBlaauw** [comment]
Can we prototype the solution with just the class_exists check and benchmark it against a couple of projects? Should be able to see some practical results. If there is hardly a difference we simply move to just checking class_exists.

**Comment by jmslbam** [comment]
Fixed in CC 0.3.0
