### ISSUE TITLE
Extend Clarkson User with the WP_User object

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#105]

**Comment by jmslbam** [comment]
@NielsdeBlaauw 

At New Scientist we needed to get the user description and thought we missed `$post->get_author()->get_description();` but the description is `metadata`. See this list
```
first_name
last_name
nickname
description
wp_capabilities (array)
admin_color (Theme of your admin page. Default is fresh.)
closedpostboxes_page
primary_blog
rich_editing
source_domain
```

So the question is, should we introduce methodes for this list or should we just suggest you use the `$user->get_meta('description')`.


WordPress does use magic methodes to get these meta values when using `get_userdata`. I kind of think adding the 

> Note: the WP_User object uses PHP 5 "magic" methods to provide some of its properties. For example:
$user_info->user_login is shorthand for $user_info->data->user_login, and
$user_info->rich_editing is shorthand for get_user_meta($user_info->ID, 'rich_editing', true).

**Comment by NielsdeBlaauw** [comment]
For now we can either use `$clarkson_user->get_meta('description')` or `$clarkson_user->get_user()->description`. Both have *very* little overhead, as they both use the existing WP_User object. 

Adding these methods would just be a layer on top of a part of WordPress where it is pretty usable already.
