### ISSUE TITLE
Add extra check if Clarkson_Core_Autoloader exists

### ISSUE THREAD

**Issue by JosAchterberg** [level-level/Clarkson-Core#111]
Like Enfold

Sometimes it happends that when switching to theme that doesn't loads
Clarkson_Core via their composer.json but Clarkson Core is installed as
a mu-plugins without it's own vendor folder, then this would trigger
a fatal error. This makes switching themes to easily debug less error
prone.

**Comment by jmslbam** [comment]
Sometimes it happends that when switching to theme that doesn't loads
Clarkson_Core via their composer.json but Clarkson Core is installed as
a mu-plugins without it's own vendor folder, then this would trigger
a fatal error. This makes switching themes to easily debug less error
prone.
