### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by rianrietveld** [level-level/Clarkson-Core#123]
Make strings translatable.
In  #118 I added the text domain `clarkson-core` and the direcory `/lang/`.
After adding the text domain to the strings a pot file can be generated.

**Comment by NielsdeBlaauw** [comment]
I've looked into all strings currently in Clarkson core. There is a [single string that is translated](https://github.com/level-level/Clarkson-Core/blob/0.3.2/wordpress-objects/Clarkson_Object.php#L45). It is however a developer notice, so it should not be user-facing at any time. I will remove this translation. This way we don't have to implement and extra build step for now.
