### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by rianrietveld** [level-level/Clarkson-Core#127]
@jmslbam already stated this in branche 
https://github.com/level-level/Clarkson-Core/tree/feature/travis

**Comment by NielsdeBlaauw** [comment]
Let's continue in this branch, as the travis integration is already working correctly and should stay the same.

However we have had some new insights on the testing methodology. I'd prefer if we could get this done using the https://github.com/10up/wp_mock lib, as this has proven useful in the past.

I'll make an effort to get this started as soon as possible, and build it out from there.

We need to further discuss the starting point we want for merging a unit testing branch. Is it OK to have the testing framework complete and a base test of some core functionality? Obviously 100% coverage would be awesome but might not be worth the effort and would take too long making this change lag behind rest of development. 

My suggestion is to split this issue in three parts:
- Implement testing framework
- Identify critical functionality and implement core tests
- Set standards for ongoing improvement of coverage

Agree @rianrietveld @jmslbam ?
