### ISSUE TITLE
Refactor Clarkson Core Template class

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#130]
This file https://github.com/level-level/Clarkson-Core/blob/master/lib/clarkson-core-templates.php

- `Clarkson_Core_Templates->render()` which does a bunch of checks that isn't needs to be done. Like using the `$wp_query`. Which isn't necessary.

- Als when directly just calling the `render` function, it's not logic to need to pass `$ignore_warning = true` argument. That feels weird. I know, I need to be more specific, will do that later.

- Seperate the `template` logic from the `render` logic.

**Comment by NielsdeBlaauw** [comment]
> Seperate the template logic from the render logic.

This definitely makes sense and feels like a good improvement. Are there any public methods for the template rendering that would be moved? Or is none of this logic used by themes?
