### ISSUE TITLE
Add `term` as default option to CC autoloader to overwrite the Clarkson_Term

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#133]
Like it's possible to add `user.php` it should also an option to add `term.php`

See https://github.com/level-level/Clarkson-Core/blob/master/lib/clarkson-core-autoloader.php#L144 for the default user option.

This way we don't have to include this files manually when we want to overwrite Clarkson_Term.

We could add it here: https://github.com/level-level/Clarkson-Core/blob/master/lib/clarkson-core-autoloader.php#L100

## Default post
We don't have to fix this for `post` because that's already a CPT within WordPress.

**Comment by NielsdeBlaauw** [comment]
Will be fixed in #189 . The default term to load in the theme is `\Clarkson_Core\Object\base_term`
