### ISSUE TITLE
Performance caused by object.data.content (json)

### ISSUE THREAD

**Issue by JosAchterberg** [level-level/Clarkson-Core#16]
When many `Clarkson_Object`'s are being created, they all do a `get_post()` which has a pretty big impact performance-wise. 

Solution for now is to just do a `object.get_content()` in the twig templates, instead of calling those functions on creation of the object. 

So: `object.data.*` will not be available anymore.

We may want to find a better solution in the long run.

**Comment by jmslbam** [comment]
What about passing the post object itself `WP_Post` to the constructor instead of a `post_id`. So it uses all that data and you don't have to re-query everything?

**Comment by jmslbam** [comment]
And couldn't we use, `return apply_filter('the_content', $this-> get_raw_content() )` instead of the `setup_postdata` trick?
