### ISSUE TITLE
Fix 404 errors if detail page is not publicly query-able

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#21]
```
Uncaught exception 'Exception' with message '$post_id empty' in /srv/http/els_wp_local/current/public/app/mu-plugins/clarkson-core/vendor/twig/twig/lib/Twig/Template.php on line 380
( ! ) Exception: $post_id empty in public/app/mu-plugins/clarkson-core/post-objects/Clarkson_Object.php on line 18
```

https://codex.wordpress.org/Function_Reference/register_post_type#publicly_queryable op false zetten als ik het me goed herinner
of https://codex.wordpress.org/Function_Reference/register_post_type#public op false zetten. Weet even niet meer precies hoe dit kwam.

**Comment by NielsdeBlaauw** [comment]
This problem seems like something the implementing theme should fix.

For a call of `new Clarkson_Object(null)` it seems reasonable to throw an exception. Also, since previous edits creating a Clarkson_Object without a post object is deprecated.
