### ISSUE TITLE
Template naming

### ISSUE THREAD

**Issue by kevinpoot** [level-level/Clarkson-Core#230]
Add option to twig templates to give them a seperate name like WP does.

For example: 
```
<?php
/**
* Template Name: Full Width Page
*/
```

**Comment by NielsdeBlaauw** [comment]
I think an easier, intermediate solution would be to add a filter around https://github.com/level-level/Clarkson-Core/blob/832eeb86f915d6cd26ca1e5461cc1bbec311d029/src/Templates.php#L336 to allow themes and plugins to adjust the template name. This has the added benefit of making the template name translatable.
