### ISSUE TITLE
ACF conditional page template drop down not filled with `page-templatename.twig`

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#25]
- [x] Use `basename($path)`  here https://github.com/level-level/Clarkson-Core/blob/master/lib/clarkson-core-templates.php#L169  
Because documentation says  `Array of page templates. Keys are filenames,`
- [x] Check why ACF dropdown doesn't gets filled.  
ACF uses `get_page_templates`,  and I think our alternation of the cache `page_templates` is to late?
- [x] Use ACF filter to fill location list

**Comment by ThePoit** [comment]
Same goes for `is_page_template` check in pre_get_post bijv.? cc Marco

**Comment by jmslbam** [comment]
Added filter to fill this list via `acf/location/rule_values/page_template`
