### ISSUE TITLE
Term object not correctly getting loaded

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#43]
https://github.com/level-level/Clarkson-Core/commit/1e5c0379b92891438a35eb00e4956a573112822e

**Comment by NielsdeBlaauw** [comment]
From a previous commit a buggy class seems to have the following properties:

- Class file: `post-objects/cd_tax_country.php`
- Class name: `class Cd_Tax_Country`
- Taxonomy named in file: `cd_tax_country`
- Taxonomy file: `taxonomies/cd_tax_country.php`
- Taxonomy-name: `cd_tax_country `

**Comment by jmslbam** [comment]
So the class name should be renamed to `cd_tax_country`?
