### ISSUE TITLE
PHP Fatal error:  Can't use method return value in write context 

### ISSUE THREAD

**Issue by ThePoit** [level-level/Clarkson-Core#46]
in Clarkson-Core/lib/clarkson-core-templates.php on line 206:
```
if ( !method_exists($theme, 'get_page_templates') || empty( $theme->get_page_templates() ) ) {
```

`empty( $theme->get_page_templates() )` zorgt voor bovengenoemde fatal error. Mogelijk PHP issue

**Comment by NielsdeBlaauw** [comment]
Bekend probleem in php < 5.5

> Note:
> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

Zie ook [de docs voor empty()](http://us3.php.net/manual/en/function.empty.php#refsect1-function.empty-parameters)
