### ISSUE TITLE
`get_json` method missing on Clarkson_Object

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#59]
As mentioned by @marcwieland95 in an e-mail. Out-of-the box the default `json` enpoint in Clarkson Theme / Core doesn't work. 
Solution could be to add the method `get_json` to the default Clarkson_Object.

What was you solution @marcwieland95?

@NielsdeBlaauw said we could use implement JSONSerialize instead of implementing a custom solution. http://php.net/manual/en/jsonserializable.jsonserialize.php

We didn't notice this bug because we added it to our own custom classes that extended Clarkson_Object...

**Comment by marcwieland95** [comment]
I created a really quick fix to the endpoint. Clarkson returns an empty array (object) at the time.

I forked Clarkson Core and made my adjustments. Have a look to my quick solution here:
https://github.com/marcwieland95/Clarkson-Core/commit/9dcd1444249ddb0e1c973073666f42fc2ad38c65

It's not really good tested.

Implementing a json serializer would be a good idea. I like the feature in general.
