### ISSUE TITLE
Parse error bij twig 2.0

### ISSUE THREAD

**Issue by marcoboekestijn** [level-level/Clarkson-Core#67]
bij een update naar twig 2.0 in Clarkson krijg ik een parse error:

Parse error: syntax error, unexpected `'.'` in `/srv/www/levellevel_2017/www/wp-content/mu-plugins/clarkson-core/vendor/twig/twig/lib/Twig/Extension/Core.php` on line 1549

**Comment by jmslbam** [comment]
Line 1549 says `$ret = $object->$method(...$arguments);` which is a commit from 24 days old https://github.com/twigphp/Twig/commit/640568437f673a5f18ea6878c0f93d22531effde

**Comment by jmslbam** [comment]
@marcoboekestijn heb je dit probleem nog een keer tegengekomen?

**Comment by jmslbam** [comment]
Not encountering this anymore to closing it.
