### ISSUE TITLE
Clarkson template

### ISSUE THREAD

**Issue by gtamborero** [level-level/Clarkson-Core#71]
Hi guys!
I installed  the plugin and thought I have to start my Zero template with twig... but I saw I can use the clarkson theme! (https://github.com/level-level/Clarkson-Theme) 
So It could be good to have this info on the http://wp-clarkson.com/core/ documentation ;)
Gracias Jaime! Nos conocimos en la Wp Camp de Barcelona en la cena.

**Comment by jmslbam** [comment]
Hola Guillermo! Yes I remember you from the diner, I had a great evening! How cool that you have tried Clarkson. I hope the Clarkson Theme was clear enough to start with. I have added a reference to the Theme on the Clarkson Core part like you suggested. If you have any question or other tips then feel free to ask.

Recuerdos Jaime

**Comment by gtamborero** [comment]
Hola Jaime! Pues de momento muy bien, voy poco a poco probandolo todo con cariño porque no controlo twig ;) Las cosas que me he encontrado hasta el momento son: Que si no tienes activado el plugin de "Core" aparece "pantalla en blanco" al instalar el tema, y lo siguiente que voy a ver si puedo dejarlo listo y te hago un pull request es que yo trabajo con SCSS no LESS! :( Me parece que SCSS está un paso por delante!
Gracias y estamos en contacto !

**Comment by jmslbam** [comment]
Did you got a white screen after activating the plugin? Which installation steps did you use? 
Quickdownload, Git clone or the Composer method? http://wp-clarkson.com/core/docs. Then I will also try to reproduce the white screen.

**Comment by gtamborero** [comment]
Hola Jaime! Funciona bien la instalación pero si desactivo el plugin de core sale plantalla en blanco cuando cargo la web. (Recomendación: Escribir en pantalla algo así como: Este tema necesita el plugin de Clarkson-Core activado!) Es una tonteria ;) Ya tengo montado SCSS sobre Clarkson ;)
