### ISSUE TITLE
Check indentation in CI tooling

### ISSUE THREAD

**Issue by NielsdeBlaauw** [level-level/Clarkson-Core#77]
[We value correct indentation](https://github.com/level-level/Clarkson-Core/pull/76#discussion_r104955849). So we might aswell add a check for correct indentation in the CI tooling that is being developed in #61 . Currently it's all over the place with [spaces](https://github.com/level-level/Clarkson-Core/blob/810fa854d9d1b99dc5a85bfd05ead96a9055ce22/wordpress-objects/Clarkson_Term.php), [tabs](https://github.com/level-level/Clarkson-Core/blob/810fa854d9d1b99dc5a85bfd05ead96a9055ce22/wordpress-objects/Clarkson_Object.php) and [combinations](https://github.com/level-level/Clarkson-Core/blob/cf103d96e9daa09f7ddc5de632d68c2ca97fa3af/lib/clarkson-core-twig-extension.php#L930).

I don't have a preference which one to use, as long as we can clearly communicate which it is.

**Comment by jmslbam** [comment]
Found this from Yoast. The have create a custom config as a composer package so you can include it everywhere 👍 
https://packagist.org/packages/yoast/yoastcs
https://packagist.org/packages/yoast/wordpress-seo

**Comment by NielsdeBlaauw** [comment]
Dump of current output of the yoastCS configuration for this state (https://github.com/level-level/Clarkson-Core/tree/0b9030e51c9f9ca51005e8aad7bc56930865a476).

Issues that arise are mostly:

- Indentation
- Missing docblocks
- Incorrect spacing around brackets
- Method naming

Only the last one seems somewhat controversial to me, as it directly contradicts the (WordPress naming convention)[https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions]

[report.txt](https://github.com/level-level/Clarkson-Core/files/833619/report.txt)

**Comment by jmslbam** [comment]
Fixed with #83 and #85
