### ISSUE TITLE
Publish on wordpress.org repository

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#78]
We wanted to submit the plugin to the wp.org repo. It got denied because at this moment they don't allow Framework like plugin to the repo. Helaas pindakaas 😢

See full conversation in attachments:

![screencapture-secure-helpscout-net-conversation-318585361-247497-1489135989781](https://cloud.githubusercontent.com/assets/145887/23788625/9f505a82-0577-11e7-86d0-7c017567f518.png)

![screencapture-secure-helpscout-net-conversation-319690337-247562-1489136060333](https://cloud.githubusercontent.com/assets/145887/23788626/9f508ec6-0577-11e7-9d80-0a954f063413.png)

**Comment by JosAchterberg** [comment]
😞
