### ISSUE TITLE
Run second (test) project

### ISSUE THREAD

**Issue by raldenhoven** [level-level/Clarkson-Core#9]
Because untill now only Robin has used it. 
We need alpha testers.

- [x] [DroomGarage](droomgarage.com) Alpha variant - Robin - Done +!
- [x] KVGO Toolbox - Alpha variant - Robin - Done +1
- [x] Elsevier.nl - Beta - Jaime & Jos - Busy +1
- [x] Autotaalglas - Beta - Marco - Busy +?

**Comment by jmslbam** [comment]
It's working :dancers:
