### ISSUE TITLE
Use WP Core function for deprecated filters

### ISSUE THREAD

**Issue by jmslbam** [level-level/Clarkson-Core#94]
@jrfnl gave feedback to check out Core function for deprecating filters.

> Just had a brief look through the code. You may want to update it to use the WP core `do_action_deprecated()` and `apply_filters_deprecated()` methods.

> doet niet hetzelfde, maar geeft wel nette en consistente deprecated meldingen bij gebruik van de hooks.

See https://github.com/level-level/Clarkson-Core/blob/master/lib/clarkson-core-deprecated.php#L18-L21

Since WP 4.6.0 - See https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/plugin.php#L597

**Comment by NielsdeBlaauw** [comment]
I suggest simply removing the `yalla_` filter in 0.4.0 and removing the deprecated filter functionality with it.

**Comment by jmslbam** [comment]
Agree 👍🏼 Greetings from Bukit Lawang 🐒

**Comment by NielsdeBlaauw** [comment]
All deprecated calls have been removed in #186  and #189.
