### ISSUE TITLE
Single-post.twig & singular not working

### ISSUE THREAD

**Issue by christiaanstijnen** [level-level/Clarkson-Core#97]
Hi,

Clarkson 0.2.1 does not have a post type on a single post and therefore it falls back on index instead of single-post.twig.

Note: since wordpress 4.8 the filter '{$type}_template' is updated with 'type' and 'templates'. Templates is a list of template candidates, in descending order of priority. Maybe we can use this?

**Comment by jmslbam** [comment]
Hi @christiaanstijnen of @Willemijnr could you test this branch `fix/get-post-type` with your project to see of it's works again. 

This doesn't work with the '$type_template' filter, but I can look into that some other time because forcing this version to 4.8 is a bit to early I think.

**Comment by christiaanstijnen** [comment]
I checked this in a project and single-post.twig seems to be loading fine now.
